re : 
 苏宁回款时间 : 
  苏宁回款时间 : ['回款日期','店铺','订单日期']
 物流费 : 
  物流费 : ['月份','店铺','售后费用','物流费','销售数量','每单费用','合计']
 vc结算单 : 
  结算单单据明细.xlsx : ['结算日期', '结算单号', '合同主体', '单据ID', '单据编号', '采购单号', '单据类型', '业务发生日期', '采购员', '开票方', '商品编码', '商品名称', '下单数量', '实收数量', '单价', '金额小计', '订单号', '客户订单号']
 京东 : 
  京东报表.xlsx : ['客户订单号', '商品编码', '品牌', '商品名称', '商品单价', '采购价', '采购单号', '退货单号', '购买数量', '收货人姓名', '收货人电话', '收货人地址', '省', '市', '县', '预计发货时间', '商家仓ID', '商家仓名称', '订单备注', '商家备注', '父单号', '支付方式', '出库时间', '下单时间', '可出库时间', '订单金额', '用户支付金额', '承运商', '运单号', '订单状态', '订单完成时间', '是否有退款申请']
 京东退货单 : 
  非图书退货订单导出.xlsx : ['退货单号', '供应商简码', '供应商名称', '商品编码', '商品名称', '合作渠道', '申请数量', '实退数量', '退货价格', '申请退货金额', '实际退货金额', '制单日期', '采购单号', '退货机构', '库房地址', '联系人', '电话号码', '邮箱', '退货备注', '是否报废', '退货来源', '退货异常信息', '共享仓编码', '共享仓名称']
 苏宁报表 : 
  苏宁报表 : ['店铺', '订单编号', '购买数量', '价格', '买家应付货款', '买家应付运费', '总金额', '订单实付款', '订单状态（头状态）', '订单下单时间']
 旺店通 : 
  旺店通.xlsx : ['订单编号', '店铺', '订单来源', '仓库', '子单原始单号', '订单状态', '订单类型', '订单退款状态', '交易时间', '子单原始子单号', '商家编码', '规格名称', '下单数量', '标价', '成交价', '分摊后价格', '实发数量', '分摊后总价']
 小柚旺店通销售管理 : 
  旺店通销售管理.xlsx : ['原始单号', '店铺名称', '发票抬头', '销售单号', '订单状态', '引用销售单号', '单据类型', '订单类型', '分销类别', '日期', '商家编码', '规格码', '规格名称', '仓库', '货品成交价', '货品数量', '货品成交总价', '小柚订单编码', '小柚机构名称', '小柚售达方', '小柚税率', '小柚单据分类', '小柚仓库名称', '处理状态', '操作者', '操作时间', '不同步类型', '不同步原因', '检查结果', '备注', '退货原因', '退换批次号']
 自采单流水账 : 
  自采单流水账.xls : ['销售公司', '订单编号', '单据类型', '批次号', '品牌', '物料号', '物料描述', '商品规格', '型号描述', '颜色', '数量', '单位', '采购价', '采购金额', '创建时间']
 自采销售单流水账 : 
  自采销售单流水账.xlsx : ['单号', '单据类型', '自采单号', '批次号', '物料号', '品牌', '型号名称', '颜色', '物料名称', '商品规格', '采购单价', '销售单价', '数量', '采购金额', '销售金额', '交货数量', '销售批次号', '首次过账时间', '最后过账时间', '采购金额（人民币）', '销售币种汇率', '销售金额（人民币）', '退货原因', '退换批次号']
 猫宁销售订单列表 : 
  销售订单列表 : ['销售订单编号', '渠道单状态', '供应商会员名', '分销商会员名', '消费者留言', '分销单创建时间', '分销单付款时间', '分销单发货时间', '分销单退款成功时间', '分销单确认收货时间', '经营模式', '支付方式', '渠道产品名称', '产品SKU名称', '商家编码', '销售数量', '渠道价格(元)', '分销金额小记(元)', '改价金额(元)', '分销金额小记汇总(元)', '分销邮费(元)', '分销单金额汇总(元)', '分销商已支付金额(元)', '备注文字', '备注颜色', '分销单退款状态', '已退款金额(元)', '消费者订单编号', '消费者订单支付状态', '消费者支付宝交易号', '分销商支付宝交易号', '收货人', '手机', '电话', '省', '市', '区', '地址']
 电竞业务数据 :
  商品明细.xls : ['日期', '商品ID','商品名称', '货号', '访客数', '浏览量', '商品关注数', '加购商品件数', '加购人数', '成交客户数', '成交单量', '成交商品件数', '成交金额', '成交转化率', 'UV价值', '最近上架时间', '详情页跳出率', '曝光量', '点击次数', '点击率', '系统预测未来7天销量', '下单客户数', '下单商品件数', '下单金额', '下单成交转化率', '下单转化率', 'PV现货率']
 商家榜单 :
  商家榜单.xls : ['排名', '日期', '渠道', '行业名称', '商家名称', '成交金额指数', '成交单量指数', '关注人数', '访客指数', '搜索点击指数']
 商品榜单 : 
  商品榜单.xls : ['序号', '日期', '渠道', '行业名称', '商品名称', '成交金额指数', '访客指数', '搜索点击指数', '关注人数', '成交单量指数']
 电竞行业数据 :
  行业大盘走势.xls : ['序号', '日期', '渠道', '行业名称', '浏览量', '访客指数', '关注人数', '加购人数', '加购件数', '成交转化率', '成交金额指数', '成交单量指数', '成交件数指数', '成交客单价', '行业店铺数', '行业动销店铺数', '搜索点击人气', '搜索点击指数', '搜索点击率指数', '曝光店铺数', '曝光商品数']
 电竞流量数据 :
  流量概况.xls : ['日期', '全部渠道', '访客数', '浏览量', '跳失率','人均浏览量','平均停留时长（秒）','新访客数','老访客数','下单转化率','成交转化率']
 星宇_入库明细 :
  入库明细.xlsx : ['仓库', '物流公司', '状态', '经办人', '供应商编码', '供应商', '采购开单日期', '采购单号', '商家编码', '供应商货品编号', '货品编号', '货品名称', '品牌', '规格名称', '规格码', '原价', '采购折后价', '入库价', '调整后单价', '采购单货品数量', '入库数量', '采购单货品总金额', '原价入库总额', '入库价总额', '单价差额', '总差额', '入库日期', '入库单号', '入库货位', '入库批次', '采购入库单备注', '货品备注']
 星宇_序列号明细 :
  序列号明细.xlsx : ['序列号', '仓库', '供应商', '类型', '创建类型', '状态', '创建编号', '修改时间', '入库单号', '采购单价']
 星宇_钱包订单明细 :
  订单明细.xlsx: ['订单编号', '单据编号', '单据类型', '商品编号', '商户订单号', '商品名称', '结算状态', '费用发生时间', '费用计费时间', '费用结算时间', '费用项', '金额', '币种', '商家应收/应付', '钱包结算备注', '店铺号', '京东门店编号', '品牌门店编号', '门店名称', '备注', '收支方向', '商品数量', '对账日期']
 星宇_钱包一盘货:
  一盘货.xlsx: ['日期', '账单日期', '流水号', '账户代码(二代会员号)', '账户名称', '币种', '收入金额(元)', '支出金额(元)', '账户余额(元)', '交易类型', '费用类型', '商户订单号', '原商户订单号', '交易备注', '对方户名', '对方账户', '代付退票失败原因', '记账请求号', '交易订单号', '业务订单号']
 旺店通_出库序列号明细:
  出库.xlsx: ['序列号', '序列号类型', 'SN码状态', '商家编码', '货品编号', '货品名称', '规格码', '规格名称', '出库单编号', '出库单状态', '原始单号', '订单编号', '订单类型', '仓库', '店铺', '物流公司', '物流单号', '收件人', '客户网名', '省份', '城市', '地区', '地址', '邮资', '手机', '固话', '发货时间']
 旺店通_出库单明细:
  出库明细.xlsx: ['订单编号', '原始单号', '子单原始单号', '原始子订单号', '订单类型', '出库单编号', '仓库', '仓库类型', '店铺', '出库单状态', '出库状态', '分拣序号', '商家编码', '货品编号', '货品名称', '货品简称', '规格名称', '条形码', '货品数量', '货品原单价', '货品原总金额', '订单总优惠', '邮费', '货品成交价', '货品成交总价', '货品总优惠', '货到付款金额', '订单支付金额', '应收金额', '退款前支付金额', '单品支付金额', '分摊邮费', '收货地区', '物流公司', '实际重量', '预估重量', '需开发票', '制单人', '打单员', '拣货员', '打包员', '检视员', '业务员', '验货员', '打印波次', '物流单打印状态', '发货单打印状态', '分拣单打印状态', '物流单号', '分拣单编号', '付款时间', '发货时间']
 旺店通_销售明细:
  销售明细.xlsx: ['订单编号', '店铺', '订单来源', '仓库', '子单原始单号', '订单状态', '订单类型', '货到付款', '订单退款状态', '交易时间', '付款时间', '货品名称', '规格名称', '平台货品名称', '平台规格名称', '下单数量', '标价', '货品总优惠', '成交价', '分摊后价格', '折扣', '实发数量', '分摊后总价', '退款前支付金额', '分摊邮费', '单品支付金额']

path : './每日/excel/'

database_c :
 host : "127.0.0.1"
 port : 3306
 user : "root"
 password : "12345678"
 database : "bi"
 charset : "utf8"

select :
 vc结算单 :
  'select max(结算日期) from vc结算单' : https://vcf.jd.com/sub_finance/jxSettlerequest/search/list
 京东 :
  'select max(下单时间) from 京东' : https://pdropship.jd.com/exportCenter/initListPage
 京东退货单 :
  'select max(制单日期)  from 京东退货单' : https://vcreturns.jd.com/returns/orderList
 苏宁报表 :
  'select max(订单下单时间) from 苏宁报表' : 'NULL'
 旺店通 :
  'select max(交易时间) from 旺店通' : 'NULL'
 小柚旺店通销售管理 :
  'select max(日期) from 小柚旺店通销售管理' : http://erp2.xyooou.com/Main
 自采单流水账 :
  'select max(创建时间) from 自采单流水账' : http://boss2.xyooou.com/Home/Index
 自采销售单流水账 :
  'select max(最后过账时间) from 自采销售单流水账' : http://boss2.xyooou.com/Home/Index
 电竞业务数据 :
  'select max(日期) from 电竞业务数据' : https://sz.jd.com/sz/view/indexs.html
 商家榜单 :
  'select max(日期) from 商品榜单' : https://sz.jd.com/sz/view/indexs.html
 商品榜单 :
  'select max(日期) from 商家榜单' : https://sz.jd.com/sz/view/indexs.html
 电竞行业数据 :
  'select max(日期) from 电竞行业数据' : https://sz.jd.com/sz/view/indexs.html
 电竞流量数据:
  'select max(日期) from 电竞流量数据' : https://sz.jd.com/sz/view/indexs.html
 星宇_入库明细 :
   'select max(入库日期) from 星宇_入库明细' : 'NULL'
 星宇_序列号明细:
   'select max(修改时间) from 星宇_序列号明细': 'NULL'
 星宇_钱包订单明细:
  'select max(对账日期) from 星宇_钱包订单明细': https://biz.jd.com/index.html
 星宇_钱包一盘货:
  'select max(日期) from 星宇_钱包一盘货': https://biz.jd.com/index.html
 旺店通_出库序列号明细:
  'select max(发货时间) from 旺店通_出库序列号明细': 'NULL'
 旺店通_出库单明细:
  'select max(发货时间) from 旺店通_出库序列号明细': 'NULL'
# 覆盖表 ,'旺店通_出库单明细','旺店通_销售明细'
fugai : ['自采单流水账','自采销售单流水账','电竞行业数据']