SELECT 商品ID,商品名称,
				CASE  WHEN 商品名称 
-- 																				like '%Air' 
-- 														or 商品名称 like '%air%'  
-- 														or 商品名称 
														like '%移动电源%' 
														or 商品名称 like '%品胜%' 
																												then '非手机'
							WHEN 商品名称 like '%小米%' 
														OR 商品名称 like '%Redmi%' 
														OR 商品名称 like '%红米%' 
																												then '小米'
							WHEN 商品名称 like '%APPLE%' 
														or 商品名称 like '%苹果%' 	
																												then '苹果'
							WHEN 商品名称 like '%荣耀%' 							then '荣耀'
							WHEN 商品名称 like '%华为%' 							then  '华为'
							WHEN 商品名称 like '%HUAWEIn%' 							then  '华为'
							WHEN 商品名称 like '%OPPO%' 							then 'oppo'
							WHEN 商品名称 like '%realme%' 
														or 商品名称 like '%真我%' 	
																												then 'realme'
							WHEN 商品名称 like '%酷派' 
														or 商品名称 like '%COOL%' 	
																												then '酷派'
																												
							ELSE '非手机'
							END as 品牌,
				CASE WHEN 商品名称  like '%酷派COOL20%' 				then '酷派COOL20'
				
				     WHEN 商品名称 	like '%真我Q3s%' 						then 'realme真我 Q3s'
						 WHEN 商品名称	like '%真我Q3 Pro%' 				then 'realme真我 Q3'
						 WHEN 商品名称  like '%真我GTNeo 2' 
														or 商品名称 like '%真我GT Neo2%'  
																												then 'realme真我GT Neo2'
						 
						 WHEN 商品名称  like '%荣耀X10%'  					then '荣耀X10'
						 WHEN 商品名称  like '%荣耀X20%' 						then '荣耀X20'
						 WHEN 商品名称  like '%荣耀X30%' 						then '荣耀X30'
						 WHEN 商品名称  like '%荣耀9X%' 						then '荣耀9X'
						 WHEN 商品名称  like '%荣耀play5T%' 				then '荣耀play5T'
						 WHEN 商品名称  like '%荣耀play4T%' 				then '荣耀play4T'
						 WHEN 商品名称  like '%荣耀畅玩20%' 				then '荣耀畅玩20'
						 WHEN 商品名称  like '%荣耀V40%' 						then '荣耀V40'
						 WHEN 商品名称  like '%荣耀V30%' 						then '荣耀V30'
						 WHEN 商品名称  like '%荣耀60 Pro%' 				then '荣耀60 Pro'
						 WHEN 商品名称  like '%荣耀60%' 						then '荣耀60'
						 WHEN 商品名称  like '%荣耀50 Pro%' 				then '荣耀50 Pro%'
						 WHEN 商品名称  like '%荣耀50%' 						then '荣耀50'
						 WHEN 商品名称  like '%荣耀V30%' 						then '荣耀V30'
						 WHEN 商品名称  like '%荣耀20青春版%' 			then '荣耀20青春版'
						 WHEN 商品名称  like '%荣耀20%' 						then '荣耀20'
						 WHEN 商品名称  like '%荣耀30青春版%' 			then '荣耀30青春版'
						 WHEN 商品名称  like '%荣耀30 Pro%' 				then '荣耀30 Pro'
						 WHEN 商品名称  like '%荣耀30S%' 						then '荣耀30S'
						 WHEN 商品名称  like '%荣耀30%' 						then '荣耀30'
						 WHEN 商品名称  like '%iPhone11 Pro Max%' 
														or 商品名称 like '%iPhone 11 Pro Max%' 
																												then 'iPhone11 Pro Max'
						 WHEN 商品名称  like '%iPhone11 Pro%' 			then 'iPhone11 Pro'
						 WHEN 商品名称  like '%iphone11%' 
														or 商品名称 like '%iPhone 11%' 
																												then 'iPhone11'
						 WHEN 商品名称  like '%iPhone12 Pro Max%' 	then 'iPhone12 Pro Max'
						 WHEN 商品名称  like '%iPhone12 Pro%' 			then 'iPhone12 Pro'
						 WHEN 商品名称  like '%iphone12 mini%' 			then 'iPhone12 mini'
						 WHEN 商品名称  like '%iphone12%' 					then 'iPhone12'
						 WHEN 商品名称  like '%iPhone13 Pro Max%' 
														or 商品名称 like '%iPhone 13 Pro Max%' 
																												then 'iPhone13 Pro Max'
						 WHEN 商品名称  like '%iPhone13Pro%' 				then 'iPhone13 Pro'
						 WHEN 商品名称  like '%iphone13 mini%' 			then 'iPhone13 mini'
						 WHEN 商品名称  like '%iphone13%' 
														or 商品名称 like '%iPhone 13%' 
																												then 'iPhone13'
						 WHEN 商品名称  like '%iPhone12 Pro Max%' 	then 'iPhone12 Pro Max'
						 WHEN 商品名称  like '%iPhone12 Pro%' 			then 'iPhone12 Pro'
						 WHEN 商品名称  like '%iphone12 mini%' 			then 'iPhone12 mini'
						 WHEN 商品名称  like '%iphone13%' 
														or 商品名称 like '%iPhone 12%' 
																												then 'iPhone12'
						 WHEN 商品名称  like '%iphone SE%' 					then 'iPhone SE'
						 WHEN 商品名称  like '%OPPO A11s%' 					then 'OPPO A11s'
						 WHEN 商品名称  like '%OPPO A32%' 					then 'OPPO A32'
						 WHEN 商品名称  like '%OPPO A35%' 					then 'OPPO A35'
						 WHEN 商品名称  like '%OPPO A53%' 					then 'OPPO A53'
						 WHEN 商品名称  like '%OPPO A55%' 					then 'OPPO A55'
						 WHEN 商品名称  like '%OPPO A93s%' 					then 'OPPO A93s'
						 WHEN 商品名称  like '%OPPO A93%' 					then 'OPPO A93'
						 WHEN 商品名称  like '%OPPO A72%' 					then 'OPPO A72'
						 WHEN 商品名称  like '%OPPO Find X3 Pro%' 	then 'OPPO Find X3 Pro'
						 WHEN 商品名称  like '%OPPO Find X3%' 			then 'OPPO Find X3 Pro'
						 WHEN 商品名称  like '%OPPO K7x%' 					then 'OPPO K7x'
						 WHEN 商品名称  like '%OPPO K9s%' 					then 'OPPO K9s'
						 WHEN 商品名称  like '%OPPO K9%' 						then 'OOPPO K9'
						 WHEN 商品名称  like '%OPPO Reno5 Pro+%' 		then 'OPPO Reno5 Pro+'
						 WHEN 商品名称  like '%OPPO Reno5 Pro%' 		then 'OPPO Reno5 Pro'
						 WHEN 商品名称  like '%OPPO Reno5%' 				then 'OPPO Reno5'
					   WHEN 商品名称  like '%OPPO Reno6 Pro+%' 		then 'OPPO Reno6 Pro+'
						 WHEN 商品名称  like '%OPPO Reno6 Pro%' 		then 'OPPO Reno6 Pro'
						 WHEN 商品名称  like '%OPPO Reno6%' 				then 'OPPO Reno6'
						 WHEN 商品名称  like '%OPPO Reno7 Pro+%' 		then 'OPPO Reno7 Pro+'
						 WHEN 商品名称  like '%OPPO Reno7 Pro%' 		then 'OPPO Reno7 Pro'
						 WHEN 商品名称  like '%OPPO Reno7%' 				then 'OPPO Reno7'
						 WHEN 商品名称  like '%红米Note9Pro%' 			then 'Redmi Note9 Pro'
						 WHEN 商品名称  like '%Redmi Note 9%' 			then 'Redmi Note9'
						 WHEN 商品名称  like '%Redmi Note10 Pro%' 	then 'Redmi Note10 Pro'
					   WHEN 商品名称  like '%Redmi K40 Pro%' 			then 'Redmi K40 Pro'
						 WHEN 商品名称  like '%红米K40%' 
														or 商品名称 like '%Redmi K40%' 
																												then 'Redmi K40'
						 WHEN 商品名称  like '%红米9a%' 						then '红米9a'
						 WHEN 商品名称  like '%小米MIX4%' 					then '小米MIX4'
						 WHEN 商品名称  like '%小米12X%' 						then '小米12X'
						 WHEN 商品名称  like '%小米12 Pro%' 				then '小米12 Pro'
						 WHEN 商品名称  like '%小米12%' 						then '小米12'
						 WHEN 商品名称  like '%小米11Pro%' 					then '小米11 Pro'
						 WHEN 商品名称  like '%小米11%' 						then '小米11'
						 WHEN 商品名称  like '%小米10S%' 						then '小米10S'
						 WHEN 商品名称  like '%华为P50 Pro%' 				then '华为P50 Pro'
						 WHEN 商品名称  like '%华为P40%' 
														or 商品名称 like '%华为 HUAWEI P40%' 
														or 商品名称 like '%HUAWEI P40' 
																												then '华为P40'
						 WHEN 商品名称  like '%华为nova8pro%' 			then '华为nova8 Pro '
						 WHEN 商品名称  like '%nova9pro%' 			then '华为nova9 Pro '
						 WHEN 商品名称  like '%华为nova8%' 					then '华为nova8'
						 WHEN 商品名称  like '%nova9%' 					then '华为nova9'
						 WHEN 商品名称  like '%HUAWEI nova 7 SE%' 	then '华为nova7 SE'
						 WHEN 商品名称  like '%HUAWEI nova 7 Pro%' 
																												then '华为nova7 Pro'
																												
						 WHEN 商品名称  like '%HUAWEI nova7%' 
														 or 商品名称 like '%HUAWEI nova 7 %' 
																												then '华为nova7'
						 WHEN 商品名称  like '%HUAWEI nova 6 SE%' 	then '华为nova6 SE'
						 WHEN 商品名称  like '%HUAWEI nova 6 Pro%' 
																												then '华为nova6 Pro'
						 WHEN 商品名称  like '%HUAWEI nova6%' 
														or 商品名称 like '%HUAWEI nova 6%' 
																												then '华为nova6'
						 WHEN 商品名称  like '%HUAWEI nova 5 Pro%' 
																												then '华为ova5 Pro'
						 WHEN 商品名称  like '%HUAWEI nova 5i%' 		then '华为nova5i'
						 WHEN 商品名称  like '%华为 Mate40E%' 			then '华为Mate40E'
						 WHEN 商品名称  like '%华为 Mate40%' 				then '华为Mate40'
						 END as `型号`,
        
				
			 CASE  WHEN 商品名称 like '%4+64%' or 商品名称 like '%4GB+64%' or		商品名称 like '%4G+64%' then '4G+64G'	
						 WHEN 商品名称 like '%4+128%' or 商品名称 like '%4GB+128%' or		商品名称 like '%4G+128%' then '4G+128G'
						 WHEN 商品名称 like '%4+256%' or 商品名称 like '%4GB+256%' or		商品名称 like '%4G+256%' then '4G+256G'
						 WHEN 商品名称 like '%4+512%' or 商品名称 like '%4GB+512%' or		商品名称 like '%4G+512%' then '4G+512G'
						 
						 WHEN 商品名称 like '%6+64%' or 商品名称 like '%6GB+64%' or		商品名称 like '%6G+64%' then '6G+64G'						
						 WHEN 商品名称 like '%6+128%' or 商品名称 like '%6GB+128%' or		商品名称 like '%6G+128%' then '6G+128G'
						 WHEN 商品名称 like '%6+256%' or 商品名称 like '%6GB+256%' or		商品名称 like '%6G+256%' then '6G+256G'
						 WHEN 商品名称 like '%6+512%' or 商品名称 like '%6GB+512%' or		商品名称 like '%6G+512%' then '6G+512G'

						 
						 WHEN 商品名称 like '%8+64%' or 商品名称 like '%8GB+64%' or		商品名称 like '%8G+64%' then '8G+64G'						
						 WHEN 商品名称 like '%8+128%' or 商品名称 like '%8GB+128%' or		商品名称 like '%8G+128%' then '8G+128G'
						 WHEN 商品名称 like '%8+256%' or 商品名称 like '%8GB+256%' or		商品名称 like '%8G+256%' then '8G+256G'
						 WHEN 商品名称 like '%8+512%' or 商品名称 like '%8GB+512%' or		商品名称 like '%8G+512%' then '8G+512G'
						 
						 WHEN 商品名称 like '%12+64%' or 商品名称 like '%12GB+64%' or		商品名称 like '%12G+64%' then '12G+64G'						
						 WHEN 商品名称 like '%12+128%' or 商品名称 like '%12GB+128%' or		商品名称 like '%12G+128%' then '12G+128G'
						 WHEN 商品名称 like '%12+256%' or 商品名称 like '%12GB+256%' or		商品名称 like '%12G+256%' then '12G+256G'
						 WHEN 商品名称 like '%12+512%' or 商品名称 like '%12GB+512%' or		商品名称 like '%12G+512%' then '12G+512G'
						 
						 
						 WHEN 商品名称 like '%64G%'  then '64G'
						 WHEN 商品名称 like '%128G%'  then '128G'
						 WHEN 商品名称 like '%256G%'  then '256G'
						 WHEN 商品名称 like '%512G%'  then '512G'
						 WHEN 商品名称 like '%1T%'  then '1T'
						 END as 内存	
						 
						 
FROM  `电竞业务数据`